# @package _global_
hydra:
  run:
    dir: ./outputs/${name}/${now:%Y-%m-%d--%H-%M-%S}

name: "debug"
seed: 1
job_type: 'train'
fp16: False
cpu: False
wandb: False
wandb_kwargs:
  project: found

data:
  num_classes: 20
  dataset: pascal
  train_kwargs:
    root: /data_q1_d/machine-learning-datasets/semantic-segmentation/PASCAL_VOC/VOC2012
    year: "2012"
    image_set: train
    download: False
  val_kwargs:
    root: "/data_q1_d/machine-learning-datasets/semantic-segmentation/PASCAL_VOC/VOC2012"
    year: "2012"
    image_set: "val"
    download: False
  loader:
    batch_size: 16
    num_workers: 4
    pin_memory: False
  transform:
    resize_size: 256
    crop_size: 224
    img_mean: [0.485, 0.456, 0.406]
    img_std: [0.229, 0.224, 0.225]

# Path to labels
# Example: "/data_q1_d/extra-storage/found_new/data/VOC2012/semantic_segmentations/crf/fixed/segmaps_e2_d8_pca_32"
# segments_dir: ?
segments_dir: /data_q1_d/extra-storage/found_new/data/VOC2012/semantic_segmentations/crf/fixed_15/segmaps_e2_d5_pca_0_s12

logging:
  print_freq: 50
